== El Diario de John Gratton

Con frecuencia ha
estado en mi corazón escribir una breve reseña,
con el fin de dejar constancia de los bondadosos tratos del Señor conmigo,
y de las grandes misericordias, que en Su infinito amor,
Él me ha concedido gratuitamente, más allá de mis deseos y expectativas,
para mi gran gozo y consolación. ¡Alabanzas, gracias, gloria,
honor y renombre sean dadas y atribuidas a Él, porque sólo Él es digno, Dios sobre todo,
bendito para siempre, amén! A fin de que mis hijos y otros que vayan a leer estas líneas,
se sientan animados a confiar en el Dios vivo, a echar toda su ansiedad sobre Él,
y a obedecerlo en verdad;
porque Él nunca les falla a los que ponen su confianza
en Él y permanecen en Su bendito consejo.

Cuando le plació al Señor visitarme por primera vez y hacer que Su luz brillara en mí,
la cual es ahora mi vida,
yo no era más que un niño y estaba cuidando las ovejas de mi padre;
yo era adicto al pecado y a la vanidad,
por lo que era reprendido y golpeado internamente.
Me fue hecho manifiesto que yo no estaba en el estado de salvación,
ni tenía paz verdadera en mi mente; y cada vez que consideraba seriamente mi condición,
encontraba a un acusador cerca de mí. También encontraba que Aquel
que me reprendía por el pecado y me mostraba el engaño de mi corazón,
igualmente me aconsejaba que abrazara la verdad y la justicia,
y siempre estaba conmigo para instruirme y guiarme en el camino de santidad,
y me aconsejaba que no pecara más de palabra ni de hecho,
sino que hablara siempre la verdad.
Cuando tomaba Su consejo y seguía Su guía,
me sentía tranquilo y mi carga parecía aligerarse,
y eso me animaba a seguir adelante y a poner atención a ese Espíritu bueno en mí,
que me instruía para la piedad y para evitar lo que era malo.
Encontraba, por decirlo así, dos espíritus obrando en mí,
ambos esforzándose por ganarme uno del otro.
Encontraba que el Espíritu bueno (porque así era)
siempre me aconsejaba que hiciera cosas buenas,
y cuando era obediente a Él, descubría que el espíritu malo no podía quebrantar mi paz.
Si hubiera permanecido ahí y hubiera vivido siempre
en el consejo de ese Espíritu bueno de instrucción,
y nunca me hubiera rebelado contra Él, entonces mi paz habría sido como un río.

Tenía como diez u once años cuando el Señor me visitó con la luz de Su Hijo,
y me dejó ver la vida vana y la forma en que vivía,
pues era muy dado a jugar entre muchachos rudos,
y a deleitarme grandemente jugando a las cartas, tirando al blanco y sonando campanas;
por lo cual era reprendido.
Llegué a ver que los deportes y placeres vanos eran desagradable para el Señor,
a los que yo estaba muy inclinado antes de llegar a conocer
verdaderamente a la Palabra de Dios en mi corazón y boca,
oírla y hacerla.
De hecho, yo era juzgado en mí mismo por esas cosas, pero no conocía al Juez,
pues no era más que un niño. Aún no conocía al Señor,
ni pensaba que había sido Él quien se había reunido conmigo en mi corazón y consciencia,
y me había dicho todo lo que había hecho,
y me había manifestado todas las cosas que eran reprobadas;
aunque yo había leído en las Escrituras,
que Cristo había venido a rescatar de la vana manera de vivir para servir al Dios vivo.
Que Cristo había enseñado a orar: "`Venga tu reino.
Hágase tu voluntad, como en el cielo, así también en la tierra.`"
Y que había dicho: "`...he descendido del cielo, no para hacer mi voluntad,
sino la voluntad del que me envió.`" Y que cuando
estaba a punto de tomar la amarga copa de la cruz,
había dicho: "`No se haga mi voluntad, sino la tuya.`"
Y que había dicho: "`Si alguno quiere venir en pos de mí, niéguese a sí mismo,
tome su cruz cada día, y sígame.`"
Por tanto, que la copa que Él iba a beber y el bautismo con el que iba a ser bautizado,
sería la misma copa y el mismo bautismo para ellos.
¡Oh, esto está más allá de las palabras,
o de la profundidad que puede alcanzar la sabiduría del hombre, y sin embargo,
debemos beber la copa y ser bautizados con Su bautismo!

Era Él quien aparecía en mí cuando estaba joven, aunque no lo conocía,
y a pesar de que me sentía intranquilo entre los sacerdotes asalariados, Presbiterianos,
etc., los seguía. Cuando vi que yo no vivía como debía, un temor se apoderó de mí,
me senté en el suelo y me quedé muy serio,
y pensé en vivir más cuidadosa y santamente en el porvenir.
Cuando se engendró en mí esa mente, sentí y vi aparecer la gracia de Dios,
pero no sabía lo que era,
aunque de buena gana la hubiera sostenido y hubiera conservado el disfrute de ella;
pero no lo hice.
Pues como era joven,
cuando me reunía con mis compañeros mi mente salió
de nuevo tras los deportes vanos e infantiles,
y pasatiempos tontos y pecaminosos, y me divertía en las cosas terrenales; por tanto,
caí del consejo de lo celestial y perdí la consciencia,
la vista y el sentimiento de este.
Por tanto, me sobrevino angustia y tristeza de mente.

Así viví por cinco o seis años, y en la medida que crecía en años,
así se incrementaban la angustia y la tristeza en mí. Sin embargo,
a menudo me encontraba con el Monitor celestial; a veces me reprendía fuertemente,
y a veces me instruía tiernamente.
Y por fin, me reveló claramente mi corazón, quebrantó mi paz,
hizo que Sus terrores se apoderaran de mí,
y fui herido en mi corazón. Grande era mi tristeza, y mis lágrimas muchas,
y no sabía qué hacer.

A pesar de todo, en ese estado de tristeza a veces tenía una secreta esperanza,
y esta impedía que me hundiera bajo el gran peso que estaba
sobre mí. Eso me daba el valor para orar a Dios,
aunque no sabía cómo hacerlo.
Sin embargo, yo creía que en secreto, donde nadie pudiera oírme o verme,
podía orar mejor y confesar los pecados que no quería que los hombres supieran,
y pedir perdón y poder sobre ellos.
Pero aun así,
no encontré el poder para abandonar los pecados a los que eran tan propenso,
porque no había recibido ni conocía a Aquel a quien le había sido dado todo el poder.

Poco pensaba yo que fuera Él quien me había dicho todo lo que había hecho,
y quien había escudriñado todos mis pecados secretos.
No había nada oculto para Él,
sino que discernía los pensamientos e intenciones mismas de mi corazón;
incluso yo estaba desnudo delante de Él y no podía esconderle nada.
Sin embargo, Su aparición^
footnote:[Él habla aquí de la aparición inicial e interior de Cristo,
como condenador y reprendedor de pecado.]
me parecía una cosa tan pobre, baja y despreciable, que no creía en ella;
tampoco pensaba que fuera posible encontrar a Cristo en mí,
y por eso lo buscaba en el cielo, por encima del firmamento.
Y aunque Él me había aparecido maravillosamente por medio de Su Espíritu,
aun así no lo conocí, sino que seguí rechazando Su consejo,
y no acudí a Él para ser enseñado,
aunque había esperado mucho tiempo para ser bondadoso conmigo.
¡Gloria a Su nombre, porque ciertamente me manifestó muchas cosas!

Grandes eran los dolores de mi pobre alma,
y a veces todas las cosas externas me parecían de poco valor.
Yo le clamaba al Señor que me dijera lo que Él quería que hiciera,
y que me mostrara quien era Su pueblo, el que lo adoraba correctamente,
según Su voluntad.
Leía mucho y hablaba con muchos de religión,
y corría de un lado a otro para escuchar a los que eran considerados grandes predicadores,
pero descuidaba al gran Maestro en mi propio corazón. Yo
estimaba a los sacerdotes que estaban puestos entonces,
en tiempos^
footnote:[Oliver Cromwell fue señor protector de la Mancomunidad de Inglaterra,
Escocia e Irlanda de 1653 a 1658.]
de Oliver Cromwell, e iba a escucharlos constantemente,
pero a menudo regresaba a casa lleno de tristeza,
porque no estaba satisfecho con la doctrina de elección y condenación^
footnote:[La iglesia protestante de esa época afirmaba casi unánimemente,
que Dios había predestinado a un número específico y reducido de individuos para salvación,
y en consecuencia,
que había predestinado al resto de la humanidad (la gran mayoría) a la condenación eterna.]
de ellos, lo cual me llevaba a una profunda tribulación. De hecho,
en algunos momentos estuve muy cerca de llegar a la conclusión de que había sido condenado,
ya que mi estado parecía ser un estado de pecado.

Sin embargo, yo creía que cuando los hombres estaban en Cristo eran escogidos,
pero que los que estaban fuera de Cristo estaban fuera del camino a Dios.
Porque Cristo es el elegido y el escogido de Dios, el heredero de todas las cosas,
y todos los que están en Él son coherederos con Él. Si Cristo es de ellos,
entonces todo es de ellos, y Cristo es todo,
en todos aquellos en quienes Él vive y reina.
Pero los que no están en Cristo, están condenados, sin Dios en el mundo,
muertos en delitos y pecados, y por eso todo lo que hacen son obras muertas,
oraciones muertas, predicaciones muertas, adoración y actuaciones muertas.
En realidad, muchos están buscando Al que vive entre los muertos,
entre las ordenanzas muertas, las fes muertas,
observaciones muertas y profesiones muertas.

Mis penas continuaban incrementándose, pero yo me esforzaba por obtener tranquilidad.
Leía mucho, y oraba mucho en secreto, e iba a escuchar sermones con mucho fervor.
Para entonces me había convertido en un miembro de la iglesia Presbiteriana,
ya que había estado mucho tiempo entre ellos,
y les había contado a algunos mi condición. ¡Pero ay, ay, no pudieron ayudarme, no;
ni tampoco podían ayudarse a sí mismos!
Pues me dijeron que esa era una buena condición,
y que yo debía estar atribulado por mis pecados mientras viviera,
y que incluso el mejor de los hijos de Dios siempre tenía sus defectos.
Todo esto para persuadirme a que me sentara satisfecho
antes de que fuera limpiado y lavado de mis pecados.
¡Oh, todos eran médicos nulos!
Porque estos eran los que recubrían con lodo suelto y gritaban "`paz,
paz,`" cuando no se experimenta paz alguna.
Así se incrementaban mis penas sobre mí,
y cuando la gente cantaba salmos en la '`casa del campanario`'^
footnote:[Los antiguos Amigos usaban la frase '`casa del
campanario`' para referirse a los lugares grandes de reunión,
puesto que no estaban dispuestos a usar la palabra _iglesia_
para referirse a un edificio de madera y piedra.]
estando yo presente, no me atrevía a cantar los dichos de David como los cantaban ellos;
habrían sido una mentira en mi boca.
Porque yo claramente veía que no estaba en la condición en la que había estado David,
ni podía cantar sus palabras como mi propia canción; porque si yo hubiera cantado,
habría sido una falsedad en lo que a mí se refiere.

Mi penas seguían aumentando noche y día, y mis lágrimas y temores eran también muchos.
A veces oraba secretamente al Señor y confesaba todos mis pecados,
y le imploraba perdón al Señor,
y usaba muchas palabras (puede que algunas las hubiera aprendido de los sacerdotes,
y otras eran reales en concordancia con mi estado).
Sin embargo, cuando terminaba me sentía condenado y lleno de tristeza,
y a veces mi espíritu estaba más cargado después
de haber terminado que antes de haber comenzado,
sintiéndome condenado en mí mismo por no haber orado con fe, sin dudar nada,
ni haber orado en el Espíritu de oración y súplica.

No podía encontrar reposo para mi pobre alma.
Me lamentaba profundamente porque era impío e injusto,
aunque mis vecinos pensaban mejor de mí,
pues yo veía que mis pecados y mis transgresiones eran muchas,
y creía en la Escritura que dice,
que ninguna cosa impura puede entrar en el reino de los cielos,
y que sin santidad nadie puede ver al Señor.

Yo me lamentaba profundamente,
y estaba listo a concluir que mi corazón no estaba bien ante los ojos de Dios.
Oraba mucho en privado, en establos y graneros, en la cama y campos abiertos.
Un día, estando solo en la cima de una colina, en medio de la nieve,
lloré en voz alta con fuertes clamores,
y le pedí al Señor que me mostrara mi propio corazón. Al Señor
le plació escuchar y responder mi oración en ese momento,
de modo que me permitió ver mi propio corazón de manera tal,
que supe que había sido Él quien me lo había mostrado,
para mi satisfacción. Porque lo vi claramente engañoso, y que no era un corazón bueno,
ni humilde, ni puro.
Me complació verlo y saber qué era; pero lamenté que fuera tan malo.
Esta fue la primera vez, que recuerde,
que estuve seguro de que el Señor había respondido mis oraciones.

Yo tenía una pena profunda, sí, una pena muy profunda, y mojaba mi almohada con lágrimas.
A veces estaba dispuesto a decir: "`¡Ojalá no hubiera nacido nunca!`"
Pero le agradó al Señor poner en mi mente que estuviera contento,
y que esperara Su tiempo para darme más conocimiento de Su voluntad.
Durante un tiempo viví con gran pena, temor y tribulación. ¡Oh,
fue un tiempo indescriptible!
De modo que por la mañana me alegraba que hubiera llegado el día, y en la noche,
que hubiera llegado la noche.
En realidad,
yo estaba dispuesto a pensar que ningún hombre tenía una condición como la mía.

Por esa época llegó a la corona el rey Carlos II,
y después de un tiempo se acordó y se promulgó la uniformidad^
footnote:[Se refiere a la uniformidad de religión,
ordenada y aplicada por el Estado.]--que nadie tenía
libertad de predicar en las iglesias (así llamadas),
excepto los que se conformaban, leían el libro de oración común,
y observaban las ceremonias establecidas por los Episcopales, en caso contrario,
debían guardar silencio.
Entonces, los sacerdotes Presbiterianos, a quienes yo había estimado y admirado tanto,
dieron su sermón de despedida y nos dejaron;
porque ellos mismos no querían conformarse al libro de oración común,
y por eso no se aventuraron a quedarse con sus rebaños,
lo que me hizo llorar amargamente.

Después de lo cual vino a mi mente escudriñar las Escrituras,
para ver si aquellos que el Señor enviaba a predicar
el evangelio en la demostración del Espíritu,
podían ser silenciados por orden de los hombres,
aun cuando fueran hombres en autoridad quienes lo ordenaran; y si esos,
que entonces pretendían ser Sus ministros, podían, según la Escritura,
estar libres de culpa ante el Señor al dejar sus
rebaños y congregaciones por la voluntad del hombre,
sí o no.
Porque yo creía que si Dios los había enviado y establecido,
el hombre no debía derribarlos.
Asimismo, encontré claro por las Sagradas Escrituras,
que ellos no debían callar por orden del hombre,
si en verdad el Señor los había enviado y mandado a predicar.
Que debían obedecer a Dios en lugar de obedecer al hombre,
cuando el Señor mandaba una cosa y el hombre otra--tal
como había sucedido con los tres jóvenes y con Daniel,
quienes pacientemente soportaron la ira del rey y fueron
arrojados al horno de fuego y al pozo de los leones.
Estos confiaron en Dios y Él los libró.

Y cuando los gobernantes de los judíos les ordenaron a los
apóstoles que no predicaran más en el nombre de Jesús,
ellos respondieron:
"`Juzgad si es justo delante de Dios obedecer a vosotros antes que a Dios;
porque no podemos dejar de decir lo que hemos visto y oído.`"^
footnote:[Hechos 4:20]
Y se fueron inmediatamente al templo y predicaron y enseñaron.
En el siguiente capítulo, cuando el Señor los liberó de la prisión,
fueron de nuevo al templo y enseñaron, y alguien llegó y les dijo a los gobernantes:
"`He aquí, los varones que pusisteis en la cárcel están en el templo,
y enseñan al pueblo.`"
Entonces los mandaron a traer ante el concilio, y el sumo sacerdote les dijo:
"`¿No os mandamos estrictamente que no enseñaseis en ese nombre?
Y ahora habéis llenado a Jerusalén de vuestra doctrina,
y queréis echar sobre nosotros la sangre de ese hombre.`"
Entonces Pedro y los otros apóstoles respondieron diciendo:
"`Es necesario obedecer a Dios antes que a los hombres.`"^
footnote:[Hechos 5:26-29]
Y en seguida, en sus propias caras, predicaron valientemente, no se quedaron en silencio,
ni huyeron de sus testimonios, como habían hecho los sacerdotes en aquellos días.

Y aquel competente ministro de Cristo, el apóstol Pablo, dijo:
"`...porque me es impuesta necesidad; ¡y ay de mí si no anunciare el evangelio!`"^
footnote:[1 Corintios 9:16]
Pablo y los apóstoles tenían que predicar el evangelio,
y sabían que era poderoso y eficaz; y estaban llenos del Espíritu Santo,
de modo que no podían contenerlo, ni callar,
porque si lo hubieran hecho habrían sentido el "`ay.`" Los
hombres no los pudieron callar aunque usaron la violencia,
porque ellos escogieron sufrir en lugar de callar.
Pues no se atrevían a callar,
viendo que su gran Señor y Maestro los había mandado a predicar;
ni tampoco podían callar sin traer sobre sí mismos el ay que el hombre no podía quitar.
Aunque los encarcelaron, azotaron y apedrearon, y usaron gran violencia contra ellos,
aun así testificaron (incluso frente a la cara misma de los reyes
y gobernantes ante los que fueron llevados) de su forma de adoración,
de la verdad y de la vida que es eterna, y no valoraron sus vidas,
ni las consideraron como algo valioso para sí mismos.

Reunido con el sacerdote que vivía en la parroquia donde yo vivía también,
le dije lo que pensaba.
Le conté que yo creía que si a Dios le placía preparar
y capacitar hombres para la obra del ministerio,
y los enviaba a predicar, ellos debían obedecer a Dios.
Y que si los hombre les prohibían obedecer a Dios,
ellos no debían dejar de obedecer a Dios para complacer a los hombres;
ni debían callarse por orden del hombre, si Dios les había ordenado predicar y enseñar,
como Él había hecho con Sus siervos de antaño. Que los que
Él enviaba en estos días debían ser obedientes a Dios,
aunque el hombre se disgustara y los hiciera sufrir por causa de la justicia.
Porque el Señor era Dios,
y Él los ayudaría y recompensaría en sus corazones con ciento por uno en esta vida,
y con vida eterna en el mundo por venir.
El sacerdote me dijo que él predicaba en su propia casa alquilada,
como lo había hecho Pablo en Roma, y que no estaba callado.
Pero eso no me satisfizo, porque Pablo estaba preso y ellos no.
Si ellos se hubieran quedado hasta que hubieran sido sacados y metidos en prisión,
entonces habrían hecho lo mismo que los hombres que habían confiado en Dios,
y la pregunta sería entonces,
si el hombre en verdad habría tenido poder para apartarlos
de sus rebaños. Pero habían huido y nos habían dejado.

Habiendo escudriñado las Sagradas Escrituras,
y encontrado que estos sacerdotes habían actuado de manera contraria a ellas,
y que tanto el Antiguo como el Nuevo Testamento estaban en contra de ellos,
y que si hubieran sido verdaderos ministros de Cristo no habrían podido callar,
aunque hubieran entregado sus vidas '`a sabiendas
de que detrás de ellos podrían entrar lobos rapaces,`'^
footnote:[Hechos 20:29]
yo estaba completamente persuadido en mi mente, sobre los fundamentos antes mencionados,
que los Presbiterianos no eran los verdaderos ministros de Cristo.
Y sentí que mi mente se volvía contra ellos, al considerar que si Dios los había mandado,
ellos deberían haber permanecido en sus lugares,
pero que si no habían sido enviados por Dios,
entonces habían corrido antes de ser enviados,
y no eran los hombre que yo había pensado que eran, y habían sido puestos en evidencia.
Por lo tanto,
los dejé y vi que eran como aquellos de los que habló
nuestro Señor en el capítulo 10 de Juan,
que eran asalariados y no verdaderos pastores.
Porque cuando vieron llegar al lobo, dejaron al rebaño y huyeron;
pero el verdadero Pastor da Su vida por las ovejas.

Adónde ir o qué hacer, no lo sabía,
y estaba muy afligido y no sabía quiénes eran el pueblo del Señor. A menudo clamaba:
"`¡Señor, muéstrame Tu pueblo y a los que te adoran correctamente!
Te ruego que me unas a ellos y me permitas servirte, para poder disfrutar Tu presencia.`"
Si en aquel momento me hubiera unido al Señor,
y al don o gracia de Dios que aparecía en mi corazón,
y hubiera creído en él y obedecido sus enseñanzas,
entonces me habría unido al Señor en Su Espíritu,
y también habría sido llevado a los que estaban en el Espíritu antes que yo.
Porque ellos son Sus verdaderos adoradores,
los que están en el Espíritu y en Él adoran a Dios correctamente, quien es Espíritu.

Cuando los Presbiterianos fueron retirados del púlpito (y de mi corazón también),
llegaron los sacerdotes Episcopales con sus túnicas blancas,
que leían el Libro de Oración Común^
footnote:[El Libro de Oración Común,
es el libro de oración de la iglesia de Inglaterra (y de la Comunión anglicana),
que reemplazó los varios usos o ritos en latín que se estaban
llevando a cabo en diferentes partes del país,
agrupándolos en un solo volumen en inglés.]
con largas formas compuestas (de las cuales no se
menciona nada en todas las Sagradas Escrituras).
Esto era para mí como un sonido muerto y vacío, y mi espíritu se afligía con ello,
porque no encontraba absolutamente nada de la vida o poder de Dios en ellos;
así vi que ellos tenían una forma sin el poder.
En realidad, esta era la apariencia de piedad sin poder (2 Timoteo 3:5),
que la Escritura nos exhorta a evitar.
Porque el poder por el que llegaron los sacerdotes Episcopales,
era el mismo por el que se había silenciado a los otros; y por este mismo poder,
el sacerdote podía obligar a todos a comprar sus productos,^
footnote:[Por "`productos`" se refiere a "`mercancías espirituales`"
(es decir, sermones, sacramentos, ritos, etc.)
ofrecidas por los sacerdotes a cambio de los diezmos obligatorios.]
y si alguno se negaba, también podía excomulgarlo de la sinagoga.
Y luego, si alguno no había querido comprar sus productos, podía hacerlo pagar,
incluso después de haberlo expulsado.

Al oír que todos debían asistir a esa forma de culto,
yo también fui a adorar lo que no sabía. Cuando llegué,
el que iba a llevar a cabo la obra era un viejo Presbiteriano,
que había hablado mucho contra el Libro de Oración Común,
y contra las ceremonias que los hombres habían ordenado usar.
Pero en lugar de perder los grandes beneficios que anualmente
se obtenían (por orar y predicarle al pueblo),
se tragó lo que antes había vomitado.

Observé la adoración de ellos y escudriñé las Escrituras una y otra vez,
y encontré que el poder en el que se hallaban no era el poder de Dios,
sino el de los hombres.
Encontré que Dios había ordenado:
"`Las cosas que queráis que los hombres hagan con vosotros,
así también haced vosotros con ellos; porque esto es la ley y los profetas;`"^
footnote:[Mateo 7:12]
pero vi que ellos iban en contra de eso.
Que el Señor le había ordenado a Su siervo Pablo:
"`Ora en todo tiempo con toda oración y súplica en el Espíritu;`"
pero vi que las oraciones de los Episcopales estaban en un libro.
Encontré que la adoración que Dios requería era en Espíritu y en verdad; sin embargo,
vi que la adoración Episcopal era en ceremonia y cosas externas sin vida.
Encontré que el Señor había ordenado en el Nuevo Testamento, no guardar días, ni tiempos,
ni meses, ni años; no obstante, estos sacerdotes ordenaron que se observaran días,
uno tras otro.
Que el Señor les había ordenado a Sus ministros: "`De gracia recibisteis,
dad de gracia;`"^
footnote:[Mateo 10:8]
pero vi que estos no daban nada de gracia, sino que se sentaban listos para recibir,
y que incluso, obligaban a las personas a dar.
Finalmente, encontré que ellos no se ajustaban en nada a las Escrituras,
y concluí que eran como los falsos profetas de los que se hablaban en las Escrituras.

Así que me retiré y no me uní a ellos,
sino que el Señor me separó. ¡Bendito sea Su nombre para siempre,
quien ha sido misericordioso con mi alma más allá de lo que puedo expresar;
alabanzas vivas sean dadas a Su santo nombre por los siglos de los siglos!
Los dejé con sus formas muertas, sus sonidos muertos, sus obras muertas, sí,
todo me parecía muerto; y quedarme ahí, buscando Al que vive entre los muertos,
no beneficiaría en nada a mi pobre alma.
Yo tenía esta frase en mi mente: "`No sé quien tenga razón,
pero estos están equivocados.`"
Sus ojos están cegados, sus oídos están tapados, sus corazones son orgullosos, carnales,
codiciosos y ávidos de ganancia, y no benefician a las personas en nada.
Y si estos sacerdotes dejan a la gente después de diez, veinte,
treinta o cuarenta años de diezmar para ellos, las personas,
todavía no son mejores a pesar de todo el dinero que les han pagado.
Siguen siendo "`miserables pecadores`"^
footnote:[Una frase tomada del Libro de Oración Común.]
y es probable que continúen así. Pero aunque veía eso,
todavía me faltaba sabiduría para llegar a la verdadera luz que me mostraba esas cosas.
En cambio, estaba considerando en mi propia sabiduría qué hacer,
aunque no podía distinguir ni encontrar a los verdaderos adoradores.

Oí hablar de un cierto grupo de personas muy elogiadas,
que solían reunirse en casas particulares con gran temor de ser perseguidas,
pero eran muy elogiadas por grandes profesantes,
a quienes yo consideraba hombres de entendimiento.
Así que fui a sus reuniones, y hallé que algunos de ellos eran llamados Independientes,
otros Presbiterianos y otros Anabautistas.
Encontré que algunos de esta multitud mixta creían que Dios
había elegido a cierto número de personas para ser salvas,
y que había condenado al resto.
Otros de ellos sostenían la gracia gratuita,
o que Cristo había sido dado gratuitamente a todos.
Otros sostenían el bautismo en agua para niños; otros decían que no,
que nadie debía ser bautizado en agua antes de que creyera;
y otros no bautizaban del todo.
Pero lo que no encontré cuando estaba entre ellos, lo más grande de todo, fue al Señor,
ni pude ver el poder de Dios sobre ellos o entre ellos.
En cambio abundaba el orgullo, la calumnia de unos contra otros, bromas tontas,
vana conversación, conformación a las costumbres del mundo,
muchos de ellos amoldándose al punto de ir una vez a sus propias reuniones,
y otra a la '`casa del campanario,`' aunque tenían mucho que decir contra la
adoración en la '`casa del campanario.`' Vi que le temían sobremanera al hombre,
tal como parecía;
porque cuando la ley del hombre se impuso con grandes
penas sobre todas las reuniones separadas,^
footnote:[El Parlamento de Inglaterra había aprobado una ley que imponía
multas a toda persona que asistiera a una asamblea religiosa (distinta
de las de la Iglesia de Inglaterra) compuesta por cinco o más personas.
Los asistentes eran multados con cinco chelines por la primera infracción,
y con diez chelines por la segunda.
El predicador y el que ofrecía su casa para tales reuniones,
eran multados con veinte libras por la primera infracción y cuarenta por la segunda.]
se abstuvieron de reunirse y no se les encontraba,
y prefirieron guardar silencio antes que arriesgar los bienes de este mundo.
Yo seguía con gran tribulación de mente y no sabía qué hacer.
Porque yo ciertamente anhelaba al Señor, y glorificarlo era mi deseo; pero no sabía cómo.

Entonces fui a Chesterfield,
a buscar y a reunirme con las personas llamadas Independientes;
porque me gustaba el nombre, al no ver nada en el hombre de lo cual depender.
Pero estos dependían sólo de la muerte y sufrimientos de Cristo en Su propio cuerpo,
pero no habían llegado a verlo, ni a experimentar Su aparición en ellos como su vida;
tampoco habían oído Su voz, y la Palabra de Dios no permanecía en ellos.
Por tanto, estos eran profesantes muertos y árboles secos, que no daban fruto.
No obstante, predicaban la gracia gratuita, el amor universal, la redención general,
y la tierna misericordia para todos.^
footnote:[Los términos "`amor universal`" o "`redención general,`" no deben confundirse
con la doctrina de la salvación universal o la reconciliación universal.
La palabra universal fue utilizada por los primeros cuáqueros para referirse a su creencia
de que Dios ofrece la salvación a toda la humanidad (y no sólo a un pequeño número predestinado),
a través de una medida de Su luz o gracia que da
testimonio en el corazón contra el pecado,
e invita a todos a encontrar la salvación en Cristo.
Esta _invitación_ interior es lo que es universal.
Cuando se recibe, se sigue y se obedece,
esta luz se convierte en la vida y la salvación del alma.
Si se rechaza, la misma luz se convierte en la condenación del hombre.
Véase Juan 3:19-21.]
Esto me agradaba mucho más que la doctrina Presbiteriana
de la elección y condenación. Sin embargo,
yo no estaba satisfecho ni tranquilo, porque leía mucho las Escrituras,
y al leerlas (con la ayuda secreta del Todopoderoso Dios,
que Él me proporcionaba en Su infinito amor) vi que todos
los que eran conducidos y guiados por el Espíritu de Dios,
eran hijos de Dios, y que si algún hombre no tenía el Espíritu de Cristo,
no era de Él. Esta es una distinción tan clara entre los hijos
de Dios y los hijos del maligno (o los hijos de este mundo),
que no hay forma de unirlos.
Esto está claro en las Sagradas Escrituras.
Porque la luz y las tinieblas, Cristo y Belial, son opuestos;
los creyentes y los infieles no pueden unirse a menos que haya una nueva creación,
un nuevo nacimiento, el que los inconversos son alentados a esperar, buscar,
suplicar y aguardar.

Vi que sin el disfrute de Dios en mi propia alma todo era en vano.
No me servía de mucho leer y oír lo que otros hombres habían disfrutado,
mientras yo andaba sin eso,
porque sabía que no podía tomar el aceite de las vírgenes sabias y usarlo para mí. Vi
que una pequeña medida del Espíritu de Dios era más preciosa que todo este mundo vano,
y que sin ella no podía descansar.
Hice mis observaciones sobre aquellos Independientes y vi que eran muy orgullosos,
y que les temían a los hombres y a los sufrimientos.
Cuando acudíamos a las reuniones,
se nos advertía que fuéramos lo más privadamente posible;
de modo que íbamos por varios caminos, uno resguardado por el seto de un lado,
y otro resguardado por otro, para que no llamáramos la atención. Luego,
cuando llegábamos a los lugares de reunión,
se colocaban centinelas o guardianes para que,
en el caso de que apareciera un magistrado,
dieran aviso y todos pudiéramos huir y disolver nuestra
reunión. Esto me parecía incorrecto y me disgustaba,
porque veía que ellos no eran como los discípulos de Cristo,
quienes no se había avergonzado, ni temido reconocer a Cristo delante de los hombres.
Hacer eso no contribuía a difundir el evangelio, si es que lo predicaban.

No encontré entre ellos la verdadera paz con Dios,
ni el disfrute del Señor en mi pobre alma.
Con lo cual, los dejé a ellos, a todas las iglesias y personas, y continué sólo,
como alguien sin pareja ni compañía. Sin embargo,
a veces se levantaba alguna esperanza más allá de mis expectativas,
y creía que Dios tenía un pueblo en alguna parte, pero que yo no sabía quiénes eran.
Tenía miedo de unirme a cualquier grupo,
no fuera que ellos adoraran a Dios incorrectamente,
y resultara siendo culpable de idolatría, la cual,
según había observado a menudo en las Escrituras,
era ofensiva para el Señor (entre los judíos),
y había visto que Él no sólo los había exhortado duramente por medio de Sus profetas,
sino que también había enviado juicios sobre ellos por su idolatría y rebelión contra Él.

Las penas del infierno se apoderaron de mí, y los dolores mismos de la muerte me rodearon.
No sabía qué camino tomar; no podía encontrar a nadie que me consolara,
ni me echara una mano en mis lágrimas, miedos, terrores, aflicciones, asombros, amargura,
angustia y profunda tristeza.
Sin embargo,
yo estaba dispuesto a dialogar y a conversar sobre asuntos
de religión con cualquiera que quisiera hablar conmigo,
pues muchos me apreciaban.
Pero los sacerdotes que yo veía estaban en el engaño, y a veces era severo con ellos.
Mis penas eran tan grandes que a veces, mientras caminaba por llanuras y páramos,
clamaba y gritaba fuertemente al Señor,
cuando pensaba que no había nadie cerca para oírme o verme, sino sólo el Señor,
quien era el único a quien yo buscaba y de quien esperaba ayuda y liberación.

Entonces le agradó al Señor revelarme y mostrarme muchas cosas.
A veces me revelaba las Sagradas Escrituras,
y yo me sentía tremendamente asustado de pecar contra el Señor,
de modo que caminaba con mucho cuidado.
Me afligía ver a la gente vivir impíamente,
y que no podían creerse lo que se decían cuando compraban o vendían;
y temblaba cuando oía a un hombre maldecir.
A veces sentía en mi interior algo muy precioso y dulce para mí,
aunque no entendía claramente qué era,
pero si en algún momento hacía o decía algo que no era correcto,
pronto perdía la vista y sentimiento de eso.
¡Oh, se iba en un momento!
Vi que todo lo que ofendía al Dios santo y era reprensible no permanecería,
sino que toda contaminación y todo lo que estaba teñido de maldad estaba contra Él,
y me lo hizo ver, y lo condenó, y a mí también, en la medida que me uniera a ello.
¡Oh,
disfrutar esto es un consuelo más allá de las palabras para
el corazón que ama la justicia y tiene hambre de ella!

Cuando yo hablaba con una persona que no veía que yo había dicho una palabra
equivocada (pero yo la había visto y el Espíritu del Señor me había dejado verla),
aunque se me hubiera escapado sin darme cuenta,
por falta de diligente atención y vigilar como un portero,
como debería haberlo hecho--¡entonces mis penas se renovaban sobre mí,
junto con lágrimas y temores en abundancia!
Sin embargo,
había un deseo secreto en mí de morir y salir de este mundo perverso y pecaminoso,
en el que era raro encontrar un hombre o una mujer de corazón sincero.

Un Primer-día,
después de haber estado leyendo un rato y llorando otro bajo una cerca en el campo,
regresé a la casa como a la mitad del día,
y encontré que mi padre y mi madre habían llegado a vernos
(porque en ese entonces yo vivía con mi abuelo como aprendiz).
Me preocupaba que ellos me distrajeran del trato
del Señor que estaba experimentando en ese momento,
el cual era profundo.
Por la tarde caí enfermo del cuerpo, y cuando sentí que la enfermedad se apoderaba de mí,
me alegré, y tuve la esperanza de que me sacara de este mundo,
porque yo estaba claramente atribulado en mi mente.
Con todo, subyacía una esperanza secreta, de que si moría,
el Señor (quien es bondadoso y misericordioso) perdonaría
los pecados de mi infancia y juventud.

Después de que me recuperé bastante, fui al páramo a arrancar arbustos, y estando solo,
como era mi manera, me sentía muy agitado en el interior,
y empecé a pensar que lo que yo había sentido algunas veces muy dulce y precioso,
y otras veces como un pronto testigo, un reprensor,
un juez justo y condenador de toda injusticia, había sido el Espíritu Santo de Dios.
Recordé que había sido visitado con frecuencia por Él, pero que no lo había reconocido,
porque pensaba que yo no era digno de que se me diera el Espíritu Santo,
y que sería una presunción de mi parte esperarlo.
Sin embargo, en ese momento llegó a mi mente pensar mucho en Él,
y en Sus operaciones y obras en mí. Me vino a la
mente que había sido realmente el Espíritu de Verdad,
y que hacía algún tiempo que no lo sentía ni veía
Su aparición. Entonces me llené de temores,
no fuera que hubiera pecado contra el Espíritu Santo, y me invadió tal terror,
que no me atreví a quedarme en el páramo,
sino que me levanté (porque estaba tendido en el suelo) y me fui a casa.
Entonces me acordé,
qué me había hecho desear tanto la muerte el día que mis padres habían llegado a vernos,
cuando había estado leyendo y llorando mucho, y me invadió un estado de ánimo tan tierno,
que surgió una esperanza en mí de que si moría en este estado de ánimo,
el Señor tendría misericordia de mí,
por lo que estaba deseoso de morir mientras ese estado y esa esperanza continuaran.

No obstante, después de todo eso, volví a caer en tribulaciones,
y la tristeza se apoderó de mí. Por ese tiempo me encontré con un joven
que estaba insatisfecho con los asuntos de la fe y la adoración. Quedamos
en reunirnos el siguiente Primer-día en la casa de una mujer,
quien era de las llamadas Cuáqueras (pero yo no lo supe hasta después,
ni sabía mucho de ese pueblo, aunque había oído de él). Cuando llegó el día nos reunimos,
y resultó que otros dos hombres llegaron y se reunieron con nosotros,
que también eran llamados Cuáqueros, pero que llevaban poco tiempo siéndolo.
Ese día lo pasamos mayormente conversando.
Uno de los hombres era de apariencia pequeña y expresión lenta,
y no solía predicar en las reuniones, sin embargo,
ese día el poder del Señor cayó sobre él y habló de tal manera,
que alcanzó al Testigo de Dios en mí,
y pensé que ese trato del Señor había venido sobre él por misericordia a mí. Pero,
¡ay!, yo había albergado pensamientos tan duros hacia esas personas,
que regresé a casa muy afligido.
Mi clamor seguía subiendo al Señor, pidiéndole que me mostrara Sion,
la ciudad de mi Dios y quienes eran los que la habitaban.

Y aquel Primer-día,
mientras estaba solo y con gran agitación de mente acerca de estas cosas,
le plació al Señor mostrarme a Su pueblo,
a aquellos que le servían. Mientras yo caminaba por un bosque oscuro,
estaba tan agitado que apenas sabía cómo estaba.
Y cuando salí del bosque para subir una colina, tuve una visión,
y vi personas acostadas una al lado de otra en un lugar muy bajo,
más bajo que las otras partes de la tierra, donde estaban quietas y en silencio.
Las miré y brotó en mi corazón que ellas eran el pueblo del Señor.
Esto me hizo mirar seriamente para ver quiénes eran,
a fin de conocer (para mi consuelo) a los que el Señor reconocía como Su pueblo,
y vi claramente que eran los llamados Cuáqueros, una clase de gente pobre,
despreciada y baja.
Cuando me di cuenta de eso, me sentí asombrado y en gran tribulación,
porque este era un pueblo que, entre todos los demás, soportaba los mayores sufrimientos,
y era odiado, envilecido y despreciado por el resto.

Mientras caminaba, la visión terminó, pero yo estaba en un estado extraño,
y considerando el asunto, sentí un cambio en mí y supe que mi semblante estaba alterado.
Me acerqué a una pequeña aldea (mi camino pasaba a través de ella),
pero tenía la intención de evitar que me vieran tanto como pudiera,
porque había llegado a la conclusión de que se darían
cuenta de que mi semblante estaba muy alterado.
Sucedió entonces, que cuando ya casi había llegado al otro lado del pueblo,
una mujer me vio y me llamó,
aunque me alejé de ella tanto como pude y continué por el camino.
Ella me preguntó cómo estaba, y qué me afligía que tenía ese aspecto.
Le respondí poco, pero le dije: "`No muy bien.`"
Seguí adelante,
y al llegar a un muro que estaba sobre la cima de una colina alta me senté sobre él,
y ahí se me mostró que si quería ser un verdadero seguidor del Cordero,
debía abandonar el mundo, sus caminos, modas, costumbres y cultos corruptos,
y toda la vanagloria, amor y amistad con él. Vi que si entraba en obediencia al Señor,
quien misericordiosamente había escuchado mis clamores
y respondido mis respiraciones (o mejor dicho,
las respiraciones que Él había engendrado en mí), debía separarme de toda reputación,
amistad, amor y alabanzas de los hombres, en las que vivía entonces.
Que debía abandonar a mis antiguos compañeros con
los que había perdido mucho tiempo precioso,
en vanos deportes y juegos de azar, en los que vivíamos y nos deleitábamos,
junto con muchas otras cosas que yo apreciaba mucho.
Que debía dejar todo eso por el Señor, si quería escogerlo y seguirlo.

Eso me afligió mucho, porque yo no estaba muy dispuesto a perder ni esas cosas,
ni al Señor,
y gustosamente habría tenido tanto el amor de Dios como el amor de los hombres.
Me habría gustado disfrutar tanto de Dios como del mundo,
pero no podía. Mi amor hacia esas vanidades era tan grande y las apreciaba tanto,
que me resultaba muy difícil pensar en perderlo todo por Cristo.
Sí, esto era casi tan amargo para mí como una aparente muerte,
por el amor y el favor de la gente que yo valoraba tanto,
y la cruz me parecía entonces tan grande,
que por ningún medio podía persuadirme a tomarla.
Grande era el conflicto en el que estaba, y una guerra muy aguda se libraba en mí,
no obstante, no le revelé mi condición a nadie,
sino que mantuve todo en secreto para el hombre.

Pero el ojo que todo lo ve me contemplaba y no permitió que fuera vencido,
ni que el enemigo destruyera mi pobre alma, aunque Él le permitió tentarme y probarme,
hasta que le plació al Señor levantar a Su Testigo vivo en mí,
ante lo cual me maravillé. No pude decir qué era eso,
ni supe que lo que se me había aparecido era la gracia o don de Dios que
trae salvación (aunque yo lo había contristado y desobedecido),
hasta que me pareció que se reducía cada vez más y que se alejaba tanto,
que no podía ver más que un poco de su aparición. Sin embargo,
nunca me dejó completamente, aunque a menudo me rebelaba contra Él,
sino que seguía reprendiéndome, reprobándome y juzgándome.
En realidad, no podía estar en paz, porque me amaba y no me dejaba solo,
sino que esperaba para ser misericordioso conmigo, aunque yo no quería seguir Su consejo.

Yo estaba muy turbado en mi mente e insatisfecho con las cosas de la eternidad,
y mis tristezas eran profundas y nadie las conocía. Antes de llegar a casa,
el enemigo se acercó lo suficiente como para susurrar en mi oído: "`Quién sabe,
esto puede ser un truco del enemigo;`" refiriéndose a la visión. Y en
seguida apareció una parte en mí que parecía complacida con ese susurro,
y dijo: "`Es muy probable que sea así.`" Así buscó salvarse el viejo yo.
Entonces recordé que los sacerdotes de aquellos días,
habían predicado contra todas las cosas que no debían ser
buscadas en estos días. Ellos decían que las visiones,
las revelaciones y los milagros habían cesado,
y que era una presunción por parte de cualquier hombre,
esperar que el Espíritu de Dios le fuera dado ahora como antes.

Así que volví a descartar todo como algo peligroso, y no quise hacer más caso de ello.
Incluso deseé y estuve dispuesto a decir en mi corazón: "`¡Oh,
ojalá le placiera al Señor hablarle de forma audible
a algún hombre en estos tiempos peligrosos,
como hizo con Moisés, para que podamos conocer con certeza Su mente,
al ver que unos claman: '`Helo aquí;`' y otros claman: '`Helo ahí.`' Pero Cristo,
el poder de Dios, no está en ninguno de ellos.`"
Así que una gran ceguera, oscuridad y lamentable ignorancia se apoderaron de mí,
cuando rechacé el consejo del Señor y pisoteé bajo mis pies tan extraordinaria visitación,
y le volví mi espalda como obra del enemigo.
Tengo un gran motivo para admirar las misericordias del Señor hacia mí,
porque no fui completamente abandonado por Él. Porque en efecto, Su ojo seguía sobre mí,
aunque por un tiempo estuve en profundas tinieblas y aflicción,
y mi preocupación era muy grande.
En ese tiempo les consulté a muchos hombres de diferentes opiniones,
pero no encontré a alguno que pudiera ayudarme en este asunto,
porque no acudí Al que es poderoso, sobre quien es '`puesto el socorro.`' Por tanto,
yo era como un pájaro solitario en los bosques, sin pareja, sin estar unido a nadie.

En ese estado me topé con una prueba inesperada,
porque pocos días después de esto (en el Primer-día),
llegó a verme un joven que estaba lleno de preguntas, y que era un gran buscador,
y me dijo que recientemente había salido publicado un libro que
tenía los mayores misterios que alguna vez habían existido,
por lo que él sabía. Dijo que Dios le había hablado
audiblemente a un tal John Reeve de Londres (o alrededores),
y que le había revelado Su voluntad,
y le había ordenado ir a ver a un tal Lodowick Muggleton, para que él fuera su boca,
como Aarón había sido la de Moisés. Y que Dios les
había dado comisión por encima de todos los hombres,
y poder para bendecir a los que creyeran en ellos,
y maldecir a los que hablaran contra ellos; y que a los que ellos bendijeran,
eran benditos, y a los que maldijeran eran malditos por toda la eternidad;
junto con muchas otras cosas extrañas.

Yo en verdad deseaba ver el libro, porque si era cierto, era lo que había deseado;
y pensé en mi interior,
que ningún hombre se atrevería a decir una cosa así a menos que fuera realmente cierta.
A los pocos días fui a Chesterfield y lo vi, y como quien tenía mi deseo,
lo leí con avidez.
Al leer donde decía que el Señor le había hablado,
que les había dado a él y a Muggleton una comisión,
y que eran los dos testigos de los que se habla en el capítulo 11 de Apocalipsis,
yo estaba listo a creerlo.
Entonces, pedí prestado el libro y luego lo compré,
junto con otros muchos de sus libros al costo de ocho chelines, y los leí varias veces.
Concordé con él en muchas cosas, y al final estaba tan capturado por la historia,
que era probable que me engañara, así como al joven que me había hablado de esto.

Entonces le plació al Señor, en Su misericordia, visitarme de nuevo,
abrir mis ojos e iluminar mi entendimiento, y me hizo ver grandes errores en el libro,
y que sus escritos eran claramente contrarios a las Sagradas Escrituras en muchos aspectos.
Porque los que eran de esa opinión,
y eran llevados a creer en el falso profeta Muggleton (porque Reeve ya había muerto),
no tenían ningún culto.
Cuando nos reuníamos en la casa de una viuda de apellido Carter, no esperábamos en Dios,
ni hacíamos ningún otro ejercicio--ni predicar, ni orar, ni leer las Sagradas Escrituras.
No, no teníamos nada más que hacer que creer en Muggleton y ser salvos.
Así, pues, pasábamos mucho tiempo hablando y luego nos separábamos.

Vi que estaba claro en las Sagradas Escrituras,
que al Señor le agradaba que los hombres lo adoraran según Su propia voluntad,
en todas las épocas, y que fuera santificado en la asamblea de Sus santos,
y celebrado en reverencia por todos los que Lo rodeaban.
Pero no había nada de esto entre los Muggletonianos.
Y aunque el Señor había dicho: "`...donde están dos o tres congregados en mi nombre,
allí estoy yo en medio de ellos,`" ni ellos ni yo sabíamos algo de eso.
Simplemente teníamos que confiar en el nombre y poder de Muggleton, y si él nos bendecía,
éramos benditos y vivíamos como queríamos, pero si nos maldecía,
éramos malditos y no había remedio.
Encontré que esa doctrina era contraria a la doctrina de Cristo, el verdadero profeta,
quien dijo '`bendecid,
y no maldigáis.`' Descubrí que el espíritu de Muggleton
se deleitaba más en maldecir que en bendecir.
Por tanto, le escribí una carta e hice doce o catorce objeciones contra su doctrina,
y se la envié a Londres, a la que respondió con otra carta,
y en ella me remitía a sus libros, pero no respondió ninguna de las objeciones.
Me dijo que él juzgaba que yo había escrito en ignorancia y curiosidad,
y que por lo tanto, se abstenía de maldecirme hasta una nueva prueba.
Pero lo dejé y me senté convencido de que era un falso profeta.

Así, pues, yo era como un hombre en una nube; nadie veía mi caso,
y yo mismo apenas lo veía. Por ese tiempo yo estaba siendo muy tentado, y sin embargo,
en lo profundo tenía la esperanza de encontrar a Cristo en Espíritu,
y de experimentar Su Espíritu en mi propia alma.
Pues yo había entendido por las Escrituras,
que este Espíritu había sido derramado sobre toda carne, hijos e hijas,
y que sin Él no podía hacerse nada que agradara al Señor,
y que los que eran conducidos y guiados por el Espíritu Santo de Dios,
eran hijos de Dios.
Vi que toda adoración que no era en Espíritu y en verdad, no era aceptable para Dios.
Porque todos los profetas y los apóstoles habían venido en este Espíritu,
habiéndolo recibido en concordancia con la profecía de Joel 2:28,
y la promesa de Cristo en Lucas 24:49 y Hechos 2.

Después de haberme interesado en los libros de ese hombre, y de haberlos terminado,
resolví dejar de leer libros extraños, y solamente leer las Escrituras de verdad,
por medio de las cuales yo me sentía un poco tranquilo.
Sin embargo, no sabía cómo llegar a Cristo (de Quien yo tenía gran necesidad),
y estaba casi sin esperanza.
Yo conversaba con muchos, pero no encontraba verdadera paz, ni consuelo, ni satisfacción,
sino que permanecía bajo mucha tristeza en lo secreto,
y todavía no era tan sabio como para ocuparme del Don o Testigo
de Dios en mí. Si oía un mal informe de los llamados Cuáqueros,
me alegraba y me animaba a seguir menospreciando la aparición de la Verdad en mi interior.
Con todo, el amor de Dios era tan grande hacia mí,
que no quitó Su Espíritu Santo de mí. ¡Alabanzas,
alabanzas vivas a Su santo nombre por siempre!

Me mudé del lugar donde había vivido toda mi vida, y me fui a vivir a Monyash,
a seis millas de allí. Pregunté qué clase de profesantes había ahí,
y encontré a un pueblo llamado Anabautistas, de quienes sabía muy poco,
pero preferí la compañía de ellos que la de los rudos y mundanos.
Conversé mucho con ellos y les tomé cariño,
lo que me llevó a familiarizarme no sólo con sus principios,
sino también con sus prácticas de adoración, que al llegar a comprenderlas,
poco podía decir contra ellas,
al pensar que eran las que más se acercaban a las Escrituras,
de todas las otra que había probado hasta entonces.
Así que asistí a sus reuniones y estuve a punto de
persuadirme de que debía ser sumergido en el agua,
porque a menos que fuera sumergido, no podría ser admitido en su iglesia.
Al no ver más, lo habría hecho con gusto,
porque este era un camino mucho más fácil para la carne,
que la obediencia al Don de Dios en mí.

Pero no pude llegar al bautismo en agua con fe.
Porque los oí predicar que el bautismo en agua era señal de muerte,
sepultura y resurrección, y que un hombre debía estar muerto antes de ser sepultado;
pues decían:
"`Es monstruoso por naturaleza sepultar a un hombre antes de que esté muerto.`"
Entonces, al encontrar que las Sagradas Escrituras dicen: "`El que ha muerto,
ha sido liberado del pecado,`" y "`¿cómo pueden, los que han muerto al pecado,
vivir aún en él?,`" me examiné a mí mismo,
y hallé que yo no había sido liberado del pecado, por lo tanto, que no había muerto,
y en consecuencia, que no era apto para ser sepultado.
Y que antes de estar muerto y sepultado,
no podría conocer una resurrección para santidad y justicia.
Y que si iba y era sepultado bajo el agua como si hubiera muerto,
sería como una máscara y una mentira, y trataría falsamente tanto a Dios como al hombre.
Eso me mantenía fuera del agua,
pero un día uno de los principales llegó a verme y me preguntó
la razón por la que yo no había llegado a ser sumergido,
y le respondí lo anterior.
Sin embargo, me dijo: "`Vienen muchos,
que creo que son menos aptos que tú.`" Le dije que eso no significaba nada para mí,
porque yo no me atrevía.

Después de esto fui a ver a mi hermana ser sumergida en un río llamado Wye,
y tras ella a dos jóvenes.
Y cuando salieron del agua, pasé algún tiempo con ellos para observar a los que,
según ellos, habían pasado de muerte a vida.
Pero no vi ninguna aparición del Espíritu, o de novedad de vida, o poder,
o evidencia de que hubieran recibido al Espíritu Santo--siendo su bautismo sólo con agua,
el que sólo puede lavar la inmundicia de la carne.
(1 Pedro 3:21)

Pero los que son bautizados en Cristo, deben ser bautizados en Su muerte,
muriendo al pecado y siendo sepultados en la muerte por medio de Su bautismo,
para que al ser liberados del pecado, puedan llegar a tener participación en Cristo,
la resurrección y la vida, por quien son hechos vivos para Dios.
Porque en Cristo se manifiesta la vida, y la hemos visto,
y hemos probado y palpado a la buena Palabra de vida,
que es como un fuego y como un martillo que quiebra en pedazos nuestros rocosos corazones;
en verdad ha brotado agua, y hemos sentido nuestros corazones hechos nuevos,
y nuestras consciencias limpiadas,
al ser lavadas con agua pura para responder a las demandas puras del Señor.
Al ser bautizadas nuestras almas en Cristo y ser revestidas de Él,
tenemos una habitación segura en Él,
y llegamos a ver que así como nadie se salvó en el arca de Noé,
sino los pocos que estaban dentro de ella, nadie puede experimentar la salvación,
sino los que están en Cristo, el arca del pacto eterno.
Porque Él ha sido dado "`para ser un pacto para el pueblo,
una luz para alumbrar a los gentiles, para abrir sus ojos ciegos,
y para ser la salvación de Dios hasta los confines de la tierra.`"^
footnote:[Isaías 42:6-7; Hechos 13:47]
Y no hay otro nombre bajo el cielo por el que alguien pueda ser salvo,
sino por Jesucristo.
¡A él sea dada toda la gloria por los siglos de los siglos!

Descubrí que aquellos a quienes yo miraba, debían estar muertos al pecado,
según profesaban, y sin embargo, vivían en él,
y abogaban por la continuación de este durante todas sus vidas.
Entonces empecé a cuestionar su forma,
y por misericordia encontré que no era más que una forma sin vida y sin poder,
y vi claramente que no estaban en el poder ni en el Espíritu de Dios.
Así me preservó la misericordia del Señor,
y Su longanimidad fue salvación para mí. Él me sacó
de todas los inventos e imaginaciones de los hombres,
y me desvistió y desnudó. No tenía refugio, pues estas higueras no tenían más que hojas,
y yo necesitaba pan.
Estas cosas externas no producían paz, ni poder, ni vida en el interior, y no podían,
ni podrán jamás,
santificar o hacer que los que se acercan a ellas
sean perfectos en lo que respecta a la consciencia,
y por lo tanto, no pueden satisfacer al nacimiento inmortal.

Sin embargo, continué con ellos, hasta que un día, mientras estaba sentado en la reunión,
observé que los ancianos y los principales oradores
se ponían unos a otros a predicar y a orar,
diciendo: "`Hazlo tú; tú eres más capaz que yo.`"
Y así se exhortaban unos a otros, y mientras los veía y los oía,
se levantó un disgusto en mi por esas acciones, y dije en mi corazón:
"`¿Por qué se asignan esas cosas unos a otros?
Dejen que Dios las ponga en quien le plazca.`"

Seguidamente, vino sobre mí un gran poder y un peso,
y estaba en mi corazón ir y hablar en la reunión. Cuando sentí que eso se acrecentaba,
y no sabía cómo contenerlo si no cedía a hablar,
me rendí y atravesé la reunión hacia los que se habían estado tratando como se ha dicho,
y les pedí libertad para decir unas pocas palabras.
Uno de ellos me dijo que no era su costumbre consentir que
alguien hablara entre ellos antes de haber sido sumergido,
haber entrado por la puerta y haber pasado por las ordenanzas, o para ese efecto.
"`Pero,`" dijo, "`creemos que eres un hombre honesto, por tanto,
puedes tomarte la libertad.`"
Así, pues, me volví a la reunión y hablé de tal manera, que se me salieron las lágrimas.
Estaba asombrado de la condición en la que me encontraba,
pues era como una botella descorchada, y el poder del Espíritu fluía en mí,
y cuando se detuvo dejé de hablar.

El siguiente Primer-día volví a ir, y la reunión caía en turno en la casa de un anciano,
un tal Humphrey Chapman.
Por ese tiempo,
se había puesto en vigor una perversa ley contra las reuniones
religiosas celebradas de cualquier forma,
que no fuera la que estaba de acuerdo con la liturgia o práctica de la iglesia de Inglaterra,
en la que estuvieran reunidas más de cinco personas, además de la familia.
La multa era de veinte libras por la casa, veinte libras por el predicador,
y cinco chelines por cada oyente.
Pero el llamado anciano,
rechazó hacer la reunión en su casa por temor a ser multado con veinte libras.
Entonces se le ofreció la reunión a otro, que no sólo era un anciano, sino predicador,
y que había sumergido a los dos hombres antes mencionados;
pero él también se negó por temor a las veinte libras.
Entonces fue ofrecida a un tercero, quien aceptó hacerla por ese día,
aunque su casa no caía en turno.
Pero cuando vi a los otros dos rechazar la reunión en sus casas por temor a sufrir,
siendo uno de ellos un predicador,
que había sumergido a dos hombres cuando yo estaba presente,
me sentí bastante perturbado.
Porque recordé las palabras de Cristo: "`Cualquiera que me niegue delante de los hombres,
yo también le negaré delante de mi Padre que está en los cielos.`"^
footnote:[Mateo 10:33]

Una vez terminada la reunión, discutieron sobre lo que debían hacer en el futuro,
y la pregunta era dónde y cuándo debían reunirse.
En esto hubo muchas diferencias;
algunos se inclinaban a favor de reunirse en el fondo de un valle,
para ahorrarse la multa de la casa.
Y con respecto a la hora de la reunión, algunos eran partidarios de reunirse temprano,
y terminarla en el momento en que el sacerdote y
la gente venían de la '`casa del campanario`' a cenar,
pero otros eran partidarios de comenzarla en ese momento.
Unos eran de una opinión y otros de otra.
Pero había uno, al que yo quería más,
que quería que se reunieran como lo habían hecho antes.
Mientras estaba sentado y los contemplaba,
sentí el mismo poder levantarse en mí (en el que había predicado
entre ellos la semana anterior) con estas palabras:
"`Este pueblo no es el pueblo de Dios,
porque ellos no se encuentran en el poder de Dios.`"
Lo creí y me fui convencido de que así era.
Así que los dejé, y no me uní más a ellos en adoración.

Una vez más estaba solo, y no me atrevía a unirme a ninguno de esos formalistas.
Me sentía como una oveja perdida, extraviada de mi Pastor,
a quien después de un largo tiempo, recordé otra vez.
Por fin me convencí de que era realmente el don de Dios, o el Espíritu de la Verdad,
el que había venido a mí para conducirme y guiarme en el camino de la verdad.
Esto produjo en mí un gran temor y pavor,
no fuera que había agotado mi día de visitación sin abandonar mi pecado,
y me preguntaba mucho si me volvería a aparecer.
Con todo,
yo tenía una esperanza secreta que me guardaba de caer en total
desesperación. Me volví a sentir muy agitado en mi mente,
y el anhelo de mi alma era disfrutar verdaderamente
del Señor y ser un instrumento para Su gloria.
Yo ansiaba conocer Su voluntad y Su adoración, y realizarlas,
y ser unido a los que estaban unidos a Él. Era como un ave
de rapiña de muchos colores sin nadie como yo,
pues todavía no había asistido a una reunión de Cuáqueros.
Sin embargo, yo trataba de vivir entre los hombres tan santa y rectamente como podía,
y de no unirme a nadie en adoración,
por temor a ser engañado al unirme en adoración falsa o en culto voluntario e idólatra.

Entonces me quedé en casa y me alejé de todas la personas, y no me uní a nadie,
habiendo probado casi todas las persuasiones entre los Protestantes.
Yo tenía mucha tristeza en lo secreto,
y fui profundamente bautizado con el "`espíritu de juicio y devastación,`"^
footnote:[Isaías 4:4]
y experimenté algo del bautismo con el Espíritu Santo y fuego,
porque mi orgullo y vacío conocimiento, conceptos y opiniones, sí,
la fe que había obtenido por la sabiduría del hombre, fue quemada.
¡Oh, la copa de la que bebí profundamente en ese momento es indescriptible!
Cuando el Espíritu Santo apareció en mí,
el Jordán se desbordó. En verdad era profundo en ese momento,
pero en medio del juicio el Señor mostró misericordia.

Empezó a haber mucho en mi mente,
y estaba listo a concluir que lo que había sentido en mí,
realmente había sido el Espíritu del Señor,
quien había esperado en mí durante mucho tiempo, y había luchado conmigo.
Una vez les dije a dos profesantes: "`Algo apareció en mí,
algo que tenía el deseo de ser recibido y hospedado;
pero debido a que no tenía mi corazón abierto, ni me sentía inclinado a abrazarlo,
recibirlo, y ocuparme de eso, lo perdí de vista y dejé de sentirlo.`"
Aquellos a quienes les conté lo que había sucedido conmigo,
no me dijeron absolutamente nada, ni me pudieron decir lo que había sido,
aunque les pedí que me aconsejaran.
Su aparición fue apacible, mansa, humilde y gentil, y llena de buenos consejos,
sin embargo, se mantuvo firme y condenó el mal, reprobándolo,
reprendiéndolo y juzgándolo con justicia.
Así que al final estaba muy persuadido, en lo secreto de mi corazón,
de que había sido el santo y puro Espíritu de Dios; y entonces pensé que si no regresaba,
mi estado sería pavoroso, triste y deplorable.
Lloraba y me lamentaba mucho, pero nadie conocía mis tristezas sino el Señor.

En aquel tiempo no sabía qué hacer,
porque descubrí que mi anterior resolución de vivir una vida santa,
y de ser tan justo como me fuera posible, no me ayudaba a estar en paz con Dios.
En realidad, no hallaba verdadero descanso para mi pobre alma, ni de día, ni de noche,
porque me di cuenta de que no tenía poder para vivir como deseaba.
Ningún hombre podía condenarme por alguna maldad, sin embargo,
yo veía en mí mismo lo que otros no podían ver.
Me faltaba la presencia del Señor,
y sin ella mi alma no podía estar satisfecha ni encontrar verdadero reposo,
a pesar de que mi vida y conducta eran tales,
que la mayoría de los que me conocían me amaban.

Por esa época me casé y me dediqué a mantener la casa.
Después de un tiempo,
mi esposa se empeñó en hacerme ir con ella a escuchar a un sacerdote,
pero yo no me atrevía,
porque había visto que ellos estaban tan equivocados como cualquiera.
Una gran tristeza se apoderó de nosotros, y a menudo discutíamos hasta las lágrimas.
En esa condición me encontré con una gran tentación, y el enemigo buscó mi ruina,
tanto del alma como del cuerpo--todo lo cual lo guardé en secreto.
Nadie sabía la profunda tristeza en la que yo estaba de día y de noche,
porque no tenía a nadie a quien abrirle mi mente, excepto a mi esposa,
pero no me atrevía a contarle a ella,
para no preocuparla y hacerla temer por mí. Sin embargo, a veces,
buscando detenidamente encontraba una pequeña esperanza, pero era muy baja y muy pequeña.

Después de un tiempo se levantó en mí un clamor al Señor: "`¡Oh,
si yo pudiera conocer Su voluntad,
y lo que Él quiere que yo haga! ¡Si pudiera conocer a Su pueblo y Su verdadera adoración,
la que lo complace,
para poder unirme a los que están unidos a Él! ¡Si pudiera
entender bien las cosas que tienen que ver con mi paz!`"
Cuando me despertaba por la mañana, un clamor secreto se levantaba en mi corazón:
"`¡Ojalá que hoy sea el día de mi nacimiento!`"
Porque había visto que yo necesitaba nacer de nuevo y ser hecho una nueva criatura,
y mi aflicción era muy grande.
No encontraba consuelo en nada de lo que este mundo ofrecía sin el disfrute de Su presencia.
Porque tenía como '`dolores de parto`' en mi espíritu delante del Señor,
y tenía algunas esperanzas de que Él se apiadaría de mí, lo cual,
¡bendito sea Su nombre!, ahora experimento.
Porque en Su tiempo hizo que el Espíritu de Su Hijo se levantara
en mi corazón con verdadero poder y eficacia,
y claramente vi que, en verdad,
era el Espíritu de Dios al que yo había contristado por mucho tiempo.
Eso engendró en mí una tristeza piadosa, y entonces acudí a Él en busca de consejo,
y me mostró el camino de la vida, y me dio poder para ser hecho hijo de Dios.
¡Bendito sea el Señor para siempre!

Un día,
en la cosecha de maíz mientras cabalgaba en el camino
hacia Sheldon en una profunda prueba interna,
y considerando mi condición (al estar en una profunda tribulación y angustia,
y condenándome y juzgándome), le plació al Señor repentina,
inesperada e imprevistamente hacer que el Lucero de la mañana se levantara en mi corazón,
y que el Sol de justicia apareciera con salvación en Sus alas,
incluso cuando las tristezas del infierno parecían apoderarse de mí. Le
plació al Señor aparecer en mí y visitarme con la Aurora de lo alto,
en una forma muy poderosa y maravillosa, con gran misericordia, bondad, buena voluntad,
y amorosa e infinita benevolencia.
Yo estaba, en mi hombre interior, lleno de poder y de la presencia del Todopoderoso Dios.
En efecto, Su celestial y gloriosa luz brillaba en mí tan poderosamente,
que puedo decir que superaba con creces el brillo del día externo.
El ojo de mi entendimiento fue abierto,
y vi que el Espíritu Santo del Señor era el que aparecía en mí, y creí,
y no pude hacer lo contrario.

¡Oh, yo estaba alegre y mi alma estaba llena de gozo,
porque me había encontrado con el Señor,
quien yo sabía que era suficiente para enseñarme todas las cosas!
Él me dejó ver que mis pecados serían remitidos y perdonados,
en y por medio de Jesucristo.
Cristo Jesús se convirtió entonces, en mi luz y mi salvación, y brotó en mí la fe viva,
porque sentí el poder y la fuerza para creer.
Entonces vi y sentí lo que era la verdadera fe,
y supe que nunca antes había tenido esa fe verdadera y viva.
Esa fe era el don gratuito de Dios, porque brotó en Su poder,
y se mantiene en dicho poder.
También vi la vida eterna manifestada por medio de Jesucristo,
y probé la buena Palabra de Dios, y fui hecho partícipe del Espíritu Santo,
y fui iluminado.
Porque la vida se manifestó y yo la vi,
y vi que el Hijo de Dios había venido y que me había
dado entendimiento para conocer Al que es verdadero,
porque Él se reveló, o se dio a conocer en mí y para mí.

Ahora mi alma estaba vivificada y animada en Él y por Él, en quien está la vida,
y también le oía como el Pastor y Obispo de mi alma,
quien se había acercado a mi propia alma.
Me fueron abiertas las Sagradas Escrituras, para mi admiración y gozo,
y las entendía mucho más de lo que las había entendido antes.
Estas se volvieron más dulces, consoladoras y preciosas para mí,
de modo que yo me preguntaba, cómo nunca antes las había visto así,
habiéndolas leído mucho de noche y de día. Pero ahora
el Señor me había dado una medida para entenderlas,
pues eran muy claras.
Vi que ningún hombre conoce las Escrituras,
sino aquellos a quienes les es dado conocerlas por el Espíritu
Santo de Aquel que tiene la llave de David,
y quien abre y cierra como le place.

Guardé lo que había encontrado ese día,
que era para mí como la Perla de gran precio escondida en mi propio
campo (aunque la había buscado en muchas formas y profesiones).
Ahora entendía la parábola de la moneda perdida en mi propia casa,
y la de la pequeña medida de levadura escondida en tres medidas de harina,
y vi que eran mi cuerpo, mi alma y mi espíritu.
Vi que esto había estado obrando en mí durante mucho tiempo, incluso cuando no lo sabía,
con el fin de leudar toda mi masa con Su propia naturaleza divina,
la cual podía ser leudada para el bien,
por medio de la obra de ese Don bueno y perfecto que había descendido
de lo alto y me había sido dado gratuitamente por Dios.

Porque, ciertamente,
los hijos de Dios son conducidos y guiados a toda verdad por el Espíritu Santo de Verdad.
Fue Él quien hizo a David más sabio que todos sus maestros,
y lo acompañó desde su juventud, y lo capacitó para ir contra el león,
el oso y el gran Goliat en el nombre del Señor. Vi que ningún
hombre podía ser hijo de Dios sin Su Espíritu Santo,
y que ese era el conocimiento que me había faltado toda mi vida.
Me sentí contento cuando sentí y supe que se me había dado gratuitamente.
Ahora mi gran preocupación era ocuparme de Él y obedecerlo,
porque era mi Maestro y el Testigo que justificaba o acusaba según mis actos.
Era mi Reprobador e Instructor, el que me mostró todo lo que había hecho alguna vez,
y ningún pensamiento,
palabra o acto quedó escondido de Él. Me alegró haber encontrado tal Consolador,
y de que fuera derramado sobre toda carne, según la promesa en Joel 2 y Hechos 2.

Grande había sido la obra de esta medida de gracia en mí,
la cual había venido por medio de Jesucristo para
hacerme una nueva criatura en Cristo (mi vida,
luz y salvación), o para transformarme en una nueva masa,
y obrar un cambio completo en mí. Porque, en efecto, yo tenía una gran necesidad de ello,
al ser un hijo de ira en la naturaleza corrupta, como los demás. Sin embargo,
todavía no tenía un conocimiento claro de esa medida de gracia,
porque mi ignorancia era muy grande.
Y aunque la luz había brillado en mi corazón oscuro e ignorante,
y había manifestado todas las cosas que eran reprobadas,
mi oscuro corazón no la había comprendido,
ni había entendido que era la luz de Cristo la que había operado así en
mí. Porque nosotros antes vivíamos en tinieblas y en la noche de ceguera,
y sembrábamos para la carne, nos deleitábamos en la injusticia y vivíamos en el placer,
al tener nuestra mirada puesta en las cosas de abajo, y no en las de arriba.
Sí, amábamos al mundo y la alabanza de los hombres más que la de Dios,
porque el amor de Dios aún no era conocido por nosotros,
ni había sido derramado en nuestros corazones,
como para ver y sentir que ese era Su amor.
Yo estuve en una profesión religiosa sin vida,
hasta que el Señor se me apareció e hizo que la luz de Su Hijo se levantara en mi corazón,
para mi gran gozo y satisfacción. Cuando fui llevado
al conocimiento de eso (lo cual fue obra del Señor,
y maravilloso a mis ojos), mi tristeza se volvió gozo,
y sentí en gran medida el amor de Dios.
Surgió en mi corazón un gran amor hacia el Señor,
y me entristecí profundamente por haber pecado contra
Él. Sentí que se me daba el verdadero arrepentimiento,
y vi que nunca antes había sabido lo que era el verdadero arrepentimiento.

En ese momento tenía tal consciencia y seguridad del amor,
misericordia y bondad de Dios hacia mí en Cristo y por Su causa
(quien se había convertido ahora en algo precioso para mí),
que si hubiera muerto en esa hora,
estaba convencido de la felicidad y de la paz eterna de mi alma.
¡Oh, entonces todo el temor a la muerte y al infierno fue quitado!
Porque claramente sentía que mi alma estaba tan afectada por el amor de Dios,
que me afligía haber contristado a Su Espíritu Santo alguna vez,
y mi deseo de no hacerlo más era grande.
Continué regocijándome con alabanzas y acciones de gracias,
que surgían en mi corazón hacia el Señor, pues mi gozo en Él era grande,
y estaba listo a pensar que mis tristezas habían
terminado y que mis lágrimas habían sido enjugadas.
Me fue dado un nuevo cántico, que sólo podía cantar el que lo tenía,
y estaba feliz de sentir a la preciosa Verdad que Dios ama, en mi interior;
Él ciertamente ama a los que la aman, viven en ella y la obedecen.
¡Oh, fue un día feliz para mi alma! ¡Yo amaba las Sagradas Escrituras,
que nunca antes habían sido tan dulces y preciosas para mí como en ese momento!
Amaba a todas las personas,
y deseaba grandemente que fueran llevadas al conocimiento de la Verdad como yo,
porque sabía que la voluntad de Dios era que todas fueran salvas.

Así, reunido con el Señor para mi gozo y consuelo,
sentí que Su Espíritu Santo era correctamente llamado el Consolador,
que conduce y guía a toda Verdad, la que ahora me regocijaba conocer, sentir,
probar y palpar.
Entonces, volví mi mente hacia el Señor para estar en comunión con Él,
deseando saber quiénes eran Su pueblo, para unirme a ellos y adorarlo correctamente,
según Su voluntad.
Y el Señor en Su misericordia me respondió mientras oraba,
y la palabra del Señor fue tan poderosa en mi corazón,
que no pude hacer otra cosa más que creerla.
Y el Señor me dio a conocer que el pueblo llamado Cuáqueros era Su pueblo,
por encima de cualquier otro.
Cuando entendí que ese era el pueblo del Señor, sentí una parte en mí que estaba triste,
porque si hubiera sido cualquier otro pueblo,
me habría sentido con más libertad de agradar al mundo y conservar la amistad con él,
y no ser tan odiado por él. Porque este pueblo era despreciado,
perseguido y profundamente sufrido,
más que todos los demás. Otros podían huir de los sufrimientos, y a veces,
conformarse un poco, pero este pueblo se mantenía en pie y permanecía,
aunque soplara el viento, cayera la lluvia y las inundaciones lo azotaran.
Porque el Señor los había capacitado para permanecer y resistir.
¡Todas las alabanzas sean dadas a Él para siempre!

Al ver que tenía una manifestación tan clara de la Verdad,
estaba deseoso de hacer la voluntad de Dios, y tenía temor de perder el sentido,
la vista y la experiencia de lo que el Señor, en Su misericordia,
me había dado el precioso disfrute.
Le agradó a Él dejarme ver que ningún hombre podía quitarme eso, ni herir mi alma,
si no lo hacía yo mismo.
¡Oh, eso fue precioso para mi alma!
Y así, aunque yo me había sentido ofendido por los llamados Cuáqueros,
ahora los llamaba Amigos,
como Cristo había llamado a los antiguos que lo obedecían. Seguí hasta
el final de mi viaje con mi mente ejercitada en seria consideración.

Pero, mientras regresaba, el mundo fue puesto delante de mí y todo lo que yo tenía en él,
y vi que debía renunciar a todo y dejarlo ir.
Y eso no fue todo, sino que era probable que yo fuera a prisión,
y que mi esposa y mis hijos fueran llevados a la pobreza.
Pero puse mi confianza sólo en el Señor, quien es todo suficiente,
y es la porción de Su pueblo, y la roca de su seguridad para siempre, amén.

Aunque el enemigo estaba ocupado conmigo,
mi mayor preocupación era sentir que el Señor seguía conmigo,
para guardarme y ayudarme a permanecer en Él y con
Él. Y bendito y alabado sea Su nombre para siempre,
Él nunca me dejó, ni me abandonó,
aunque a veces escondía (por decirlo así) Su rostro de mí. Y cuando
he pecado o transgredido por falta de diligente vigilancia,
o permitido que mi mente vague, Él no se ha enojado para siempre.
Aunque Su Palabra ha sido para mí como una espada y como un martillo, aun así,
en el juicio el Señor ha recordado Su misericordia,
y el buen Samaritano ha venido y derramado aceite y vino,
y me ha sanado maravillosamente.
¡Alabanza, gloria y renombre sean dados a Él!

Mi satisfacción era grande y mi corazón estaba vuelto al Señor,
y mi propio semblante estaba tan alterado,
que mi esposa y los vecinos lo notaban y hablaban de ello.
Pero yo mantenía mi mente en el interior y decía poco,
excepto lo que el Señor me daba para decir,
y durante un tiempo guardé mis ejercicios para mí, y no le conté a mi esposa,
ni a nadie más. Porque todavía no había asistido a una reunión de Amigos,^
footnote:[Es decir, la Sociedad de Amigos, quienes en desprecio eran llamados Cuáqueros.]
ni había ninguno cerca del condado Peak, donde vivía entonces.

Me encontré con algunos Amigos en el mercado y conversé con ellos,
pero no les hablé de mi condición. La mayor parte del pueblo estaba agitado;
algunos hablaban bien de mí y me amaban,
otros hablaban mal de mí y me odiaban sin ninguna causa, y diferían unos de otros.
Pero después de un tiempo, muchos fueron convencidos y asistían a las reuniones.
Después de que el Señor me mostró de nuevo a Su pobre y despreciado pueblo,
me alegré cuando encontré a aquellos con quienes había de esperar en Él.

Después de un tiempo, oí de una reunión en Exton,
en la casa de una viuda de apellido Farnay, cuyo esposo había sido un Amigo honesto.
Fui y encontré a varios Amigos que habían recorrido muchas millas.
Cuando llegué,
confirmé que estos estaban en la Verdad de la que yo había sido convencido,
aunque el mundo se burlara tanto de ellos.
Se dijo poco en esa reunión,
pero me senté quieto e incliné mi espíritu delante
del Señor. Lo sentí a Él conmigo y con los Amigos,
y vi que ellos tenían sus mentes retiradas,
y que esperaban sentir Su presencia y Su poder operar en sus corazones,
y que eran adoradores espirituales que adoraban a Dios en Espíritu y verdad.
Me di cuenta de que, al igual que yo,
ellos sentían y saboreaban la bondad de Dios en ese momento;
y aunque se dijeron pocas palabras,
me sentí muy satisfecho con la reunión. Porque se
levantó una dulce melodía que recorrió la reunión,
y la presencia del Señor estuvo en medio de nosotros.
Encontré más verdadero consuelo, refrescamiento y satisfacción del Señor en esa reunión,
del que alguna vez tuve en una reunión en toda mi vida.
¡Alabado sea el Señor para siempre!

Estaba seguro de que ese era Su pueblo y que eran guiados por Su Espíritu,
por medio del cual habían llegado a entender Su voluntad,
y habían sido llevados (en sus medidas) a la verdadera obediencia de Sus mandamientos,
al estar dispuestos a llevar Su cruz, negarse a sí mismos y hacerse necios,
a fin de conocer la verdadera sabiduría. Por eso esperan en silencio,
para sentir la inspiración del Todopoderoso darles un entendimiento de las cosas de Dios,
las que el hombre natural no puede entender,
porque no espera en el Espíritu la manifestación.
También sentí tal amor en mi corazón hacia ellos,
como nunca había sentido por alguna persona.
¡Oh, ese era el amor verdadero, el amor que nadie conoce sino los que lo tienen!
También sentí el mismo amor en ellos hacia mí,
y algunos de ellos me abrasaron y se alegraron por mí,
aunque no conocía a muchos de ellos, ni ellos a mí.

Así volví a casa,
y mi pobre esposa estaba sumamente afligida porque
yo había estado entre los Amigos (los llamados Cuáqueros).
La gente de nuestro pueblo empezó a enfurecerse.
Algunos discutían conmigo; otros me maldecían (según oí); otros abogaban por mí;
otros se burlaban y se mofaban de mí siguiéndome y llamándome: "`¡Cuáquero, cuáquero!`"
Cuando los oía llamarme así,
mi corazón se alegraba y se llenaba de gozo de que se me reprochara por causa de Cristo,
y de que se me considerara digno de participar con
los Amigos en las aflicciones de Cristo,
'`que aún faltaban en Su cuerpo`' (Colosenses 1:24). Y se levantó un pensamiento:
"`Ahora tengo el nombre;
ojalá pueda ser realmente llevado a la naturaleza del pueblo de Dios.`"

Pero había varias cosas que yo no discernía claramente en ese momento.
Aunque sentía al Señor conmigo y estaba seguro de que era la verdad,
en lo secreto de mi mente tenía la intención de no imitar a los Cuáqueros.
Yo seguí quitándome el sombrero delante de los hombres,
y usando el mismo lenguaje que había usado antes.
Porque no me gustaba su lenguaje sencillo, ni su comportamiento con las personas,
y no estaba dispuesto a entrar en la práctica de
esas cosas por mera imitación a los Amigos.
Yo pensaba que agradaría más a la gente si usaba "`usted`" para una persona,
y me quitaba el sombrero ante ellos (porque a muchos les encanta que los adoren,
aunque no se debe adorar a ninguna criatura sobre la tierra).
Así, pues, mi entrada a los Amigos estuvo oculta por un tiempo,
pocos conocían lo que yo era, y lo que había visto, oído y sentido.
Sin embargo,
yo sabía que había sido el Señor el que se había encontrado conmigo en el camino,
y que había sido con tal poder,
que lo había recibido gustosamente para mi gran satisfacción y consuelo,
y creía que el Señor (cuando lo considerara apropiado) abriría
mi entendimiento y me daría comprender las Sagradas Escrituras,
lo cual, en Su gran misericordia, ha hecho maravillosamente desde entonces.

Yo tenía cuidado de retener lo que se me había dado gratuitamente,
y llegó a mi mente esperar en el Señor para saber qué quería que hiciera.
Así que esperé en mi mente para oír lo que el Señor mi Dios quería decirme.
Después de un tiempo, mientras cabalgaba por el camino y esperaba,
la palabra del Señor se levantó con gran poder en mi corazón, diciendo:
"`Habla verdad a tu prójimo.
No seas de doble lenguaje; no hagas acepción de personas.`"
Esto me satisfizo completamente,
y vi que tenía que entrar al reino de los cielos como un niño pequeño.
Que tenía que aprender a hablar y a caminar de nuevo,
y que necesitaba ser ayudado y sostenido por la secreta
mano del omnipresente y omnipotente Dios,
y tomarlo en cuenta en todo lo que dijera, y en todo mi andar y hacer.
Vi que Dios no cambia, y que conforme los hombres se vuelven realmente a Él,
llegan ser hombres veraces.

Pero ese lenguaje y manera de vivir eran duros para la '`carne
y sangre,`' que deseaba complacer a los hombres y recibir alabanza.
Yo había crecido acostumbrado a esas cosas desde que era joven,
y por eso me resultaba difícil perderlo todo.
Pero sabía que debía,
aunque los hombres se ofendieran conmigo por mi obediencia al Señor. Por tanto,
me rendí en obediencia a la voluntad de Dios, en la que encontré vida y paz para mi alma,
y gran ánimo y gozo en el Señor. Sin embargo,
esta manera de hablar y de comportarme era difícil para mí,
y era una gran cruz para mi parte natural; ayudaba a mantenerme muy bajo,
y a hacer morir al viejo hombre en mí;
me hacía estar dispuesto a ser un tonto ante los ojos del mundo,
y a ser despreciado por los hombres.

¡Y ahora,
bendito y alabado sea el Señor Dios Todopoderoso para siempre! Él ha alegrado
mi alma y ha satisfecho las respiraciones de mi espíritu.
Me ha revelado los misterios de Su reino y me ha dado una medida de Su gracia.
Ha hecho que Su luz se levante en mí y que las tinieblas huyan.
Me ha dado el verdadero pan de vida y ha alegrado mi corazón con el vino de Su reino.
Él se ha convertido en mi maestro, me he recogido en Su poder,
y me ha cubierto con el estandarte de Su amor.
Él se ha convertido en mi escondite, mi roca, mi fuerza y mi refugio;
no tengo que temer lo que el hombre pueda hacerme.
Él es mi porción, nada me faltará, y por eso sólo confío en Él,
mi ayudador en el tiempo de necesidad.
Él ha hecho en mí y para mí todas mis obras,^
footnote:[Isaías 26:12]
tanto el querer como el hacer por Su buena voluntad.
Él es suficiente recompensa para todos los que esperan en Él. Él es todo, en todos;
y no tengo a nadie más fuera de Él. Él es suficiente; no soy nada sino lo que soy en Él,
por lo que sólo Él debe ser alabado.
Toda la gloria es para Él,
porque sólo Él ha redimido mi alma de la muerte y me ha revelado el camino de la vida.
Ha quitado los grilletes de mis piernas y ha puesto mis pies sobre un fundamento seguro.
Me ha sacado de la prisión y ha puesto mi alma en un lugar agradable.
Me ha arrebatado como un tizón del fuego, y me ha dado fuerza por encima de mis enemigos.
Ha redimido mi alma de la muerte, y me ha hecho caminar por la senda de la vida.
Ha escuchado mis suspiros, y mis gemidos no le son desconocidos.
En efecto,
Él ha considerado las respiraciones de mi alma y ha convertido mi tristeza en gozo.
Sí, ha esperado con ternura para ser misericordioso conmigo,
y Su paciencia me ha conducido al arrepentimiento.

Oh, ¿qué le rendiré al Señor mi salvador, quien me ha tratado tan generosamente?
Mi alma bendice al Señor para siempre,
y todo lo que está dentro de mí alaba Su santo nombre,
pues ha hecho que la misericordia me rodee.
¡Oh, la amorosa bondad del Señor! ¡Todos ustedes que lo conocen alaben Su nombre,
porque Sus misericordias son eternas! Él ha hecho que la luz resplandezca en las tinieblas,
y por ella ha manifestado todas las cosas que son reprobadas.
A esta luz se vuelve mi corazón,
y estoy resuelto a alejarme de mis iniquidades y
servir al Señor con reverencia y temor santo.

Ahora sé que era Él, quien por medio de Su Palabra,
me mostraba mis pensamientos y las intenciones de mi corazón. Aunque antes lo ignoraba,
ahora estoy seguro de que era Su Palabra la que a menudo hablaba a mi espalda, diciendo:
"`Este es el camino,
andad por él`" (Isaías 30:21). Él seguía buscando salvarme del poder del enemigo,
aunque en ese entonces yo no lo consideraba.
Sin embargo, me persiguió, hasta que por fin mi corazón se abrió para recibirlo,
Al que ahora es mi amado y me ha dado a probar que Dios es bueno,
cuya bondad supera con creces todo lo que este mundo pueda ofrecer.
¡Alabado sea el nombre del Señor!

He hallado la Perla de gran precio, lo único que mi alma necesita conocer,
y esta es Cristo en mí, la esperanza de gloria, el verdadero camino al Padre,
y quien prometió estar con Sus discípulos hasta el fin del mundo.
Este es Aquel a quien debemos oír y obedecer en todo,
para que no seamos cortados de entre Su pueblo.^
footnote:[Hechos 3:23]
Es la unción que hemos recibido del Señor, la que enseña todas las cosas,
que es verdad y no mentira.
¡Oh, qué los hijos de los hombres abran sus corazones,
para que el Rey de gloria entre y expulse esa cueva de ladrones,
que les roba el tesoro y la paz que sobrepasa sus entendimientos!
Entonces llegarán a experimentar al Consolador, al Espíritu de Verdad,
que los lleva a toda verdad;
porque es Él quien hace todas nuestras obras en nosotros y para nosotros.
Esto es la obra del Señor y es maravillosa a nuestros ojos.
¡A Él sea toda la alabanza y la gloria por los siglos de los siglos!

[.asterism]
'''

__Después de encontrar finalmente lo que había buscado por tanto tiempo,
John Gratton continuó en fiel sumisión a Su Maestro,
y se convirtió en un notable ministro en la temprana Sociedad de Amigos.
Viajó a menudo al servicio del evangelio, declarando por toda Inglaterra, Escocia,
Irlanda y Gales lo que el Señor había hecho por él, y lo que él había "`oído,
visto y palpado tocante a la Palabra de vida.`"
Entre otras pruebas y aflicciones que fueron su porción,
fue arrestado en 1680 por incumplir con la iglesia de Inglaterra,
y encarcelado por espacio de cinco años y medio,
durante los cuales escribió muchos tratados y epístolas
edificantes para el fortalecimiento de sus hermanos.
Cuando por fin fue liberado por una proclamación
del rey Jacobo en favor de la libertad de consciencia,
reanudó sus viajes en la obra del ministerio,
y siguió siendo un obrero y anciano en la iglesia hasta su muerte en 1712,
a la edad de sesenta y nueve años. Unas de sus últimas palabras fueron:
"`Qué el Señor bendiga a Su pueblo, prospere Su verdad entre ellos,
y les permita vivir en amor unos con otros.`"
No mucho después, debilitándose muy rápido, dijo: "`Señor,
libremente te encomiendo mi alma y mi espíritu.`"__
